WorkshopForBikes/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BLL.interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Models;

namespace WorkshopForBikes.Controllers
{
    public class CustomerController : Controller
    {
        ICustomerService service;

        public CustomerController(ICustomerService _service)
        {
            service = _service;
        }
     

        public IActionResult Index()
        {
            List<Customer> customers = service.GetAllCustomers();

            return View(customers);
        }

        
        
        public IActionResult Create()
        {
            return View();
        }
        
        
        //Post:
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("CustomerId, FirstName, Name")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                service.Add(customer);
                return RedirectToAction("Index");
            }
            return View(customer);
        }



        public IActionResult Edit(int customerId)
        {

            Customer customer = service.FindById(customerId);
            return View(customer);
        }


        //Post:
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int CustomerId, [Bind("CustomerId, FirstName, Name")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    service.Update(customer);
                }
                catch (DbUpdateConcurrencyException)
                {
                    throw;
                }
                return RedirectToAction("Index");

            }
            return View(customer);
        }


        public IActionResult Remove(int customerId)
        {

            service.Remove(customerId);
            return RedirectToAction("Index");
        }


    }
}

WorkshopForBikes/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BLL.interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Models;

namespace WorkshopForBikes.Controllers
{
    public class ProductController : Controller
    {
        public static int productQty = 0;

        IProductService service;

        public ProductController(IProductService _service)
        {
            service = _service;
        }

        public IActionResult Index(int? shoppingBagId, int? customerId)
        {
            if (shoppingBagId!=null || shoppingBagId<1)
            {
                HomeController.shoppingBagId = shoppingBagId.Value;
            }
            if (customerId!=null || customerId<1)
            {
                HomeController.customerId = customerId.Value;
            }

            List<Product> products = service.GetAllProducts();
            //products.OrderBy(p => p.Name);
            //ViewData["products"] = products;
            
            return View(products);
        }



        public IActionResult Create()
        {
            return View();
        }

        //Post:
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("ProductId, Name, Price")] Product product)
        {
            if (ModelState.IsValid)
            {
                service.Add(product);
                return RedirectToAction("Index");
            }
            return View(product);
        }

        public IActionResult Edit(int productId)
        {
            Product product = service.FindById(productId);
            return View(product);
        }


        //Post:
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int ProductID, [Bind("ProductId, Name, Price")] Product product)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    service.Update(product);
                }
                catch (DbUpdateConcurrencyException)
                {
                    throw;
                }
                return RedirectToAction("Index");

            }
            return View(product);
        }


        public IActionResult Remove(int productId)
        {

            service.Remove(productId);
            return RedirectToAction("Index");
        }

        public IActionResult BuyProduct(int productId, int? shoppingBagId)
        {
            Product product = service.FindById(productId);
            ViewData["shoppingBagId"] = shoppingBagId;
            ViewData["productQty"] = 0;

            return View(product);
        }


        //Post:
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult BuyProduct(int ProductID, int qty, [Bind("ProductId, Name, Price")] Product product)
        {
            int customerId = 0;

            if (HomeController.customerId>0)
            {
                customerId = HomeController.customerId;
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }

            if (ModelState.IsValid)
            {
                return RedirectToAction("Create", "ShoppingBag", new { ProductID, qty });
            }
            return View(product);
        }


        //public IActionResult SpecificProduct(int productId)
        //{

        //    Product product = service.FindById(productId);


        //    //List<Product> products = service.GetAllProducts();
        //    //ViewData["ProductId"] = productId;


        //    return View(product);
        //}
    }
}

WorkshopForBikes/Views/Shared/_MainLayout.cshtml
@{
    ViewData["Title"] = "";
}

<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    @*<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">*@
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    @*<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">*@
    @*<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>*@
    <link rel="stylesheet" href="~/css/site.css" />

    <title>@ViewData["Title"] - Webshop for bikes</title>

</head>
<body>
    @*<nav class="navbar navbar-dark bg-dark">

            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
            <a class="navbar-brand" asp-area="" asp-controller="Product" asp-action="Index">Products</a>
            <a class="navbar-brand" asp-area="" asp-controller="Shopping Bag" asp-action="Index">Shopping Bag</a>

            <p class="navbar-text">Some text</p>

        </nav>*@

    @*<div class="container">
            @RenderBody()

            <h3>Navbar Text</h3>
            <p>Use the .navbar-text class to vertical align any elements inside the navbar that are not links (ensures proper padding).</p>
        </div>*@

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        @*<a class="navbar-brand" href="#">B</a>*@
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="navbar-brand" asp-area="" asp-controller="Customer" asp-action="Index">Customers</a>
                </li>
                <li class="nav-item">
                    <a class="navbar-brand" asp-area="" asp-controller="Product" asp-action="Index">Products</a>
                </li>

                <li class="nav-item">
                    <a class="navbar-brand" asp-area="" asp-controller="ShoppingBag" asp-action="Index">Shopping Bag</a>
                </li>
                <li>
                    <a asp-controller="ShoppingBag" asp-action="Edit" asp-route-shoppingBagId="@HomeController.shoppingBagId" class="btn btn-info btn-lg">
                        @*<span class="glyphicon glyphicon-shopping-cart"></span>*@
                        <img src="~/images/bikes/icon_shopping_cart.png" style="max-width:25px;max-height:25px;" />Shopping Cart
                    </a>
                </li>
            </ul>
                @*<li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Dropdown
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>*@
</div>
    </nav>
    <hr />

    @*<h1>Workshop for bikes - @ViewData["Titel"]</h1>*@
    @*<div class="container body-content">
            @RenderBody()
        </div>*@

    <div class="container body-content">
        @*<partial name="_CookieConsentPartial" />*@
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <hr />
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Workshop for Bikes
        </div>
    </footer>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>